channels:
  - pytorch
  - conda-forge

name: pykitPIV

dependencies:
  - pip
  - python=3.10
  - pytorch
  - pandas
  - pip :
    - jupyterlab
    - matplotlib
    - h5py
    #- torch
    #- pandas
    - scipy
    - Sphinx
    - sphinxcontrib-bibtex
    - furo
